### PR TITLE
Add an RSS feed

### PR DESCRIPTION
**Pull request by Vinnl**
This project looks interesting and I'd like to subscribe to updates on the blog, but it does not appear to provide an RSS feed. This pull request should enable them.

### CODE REVIEW

**Comment by xolotl** [comment]
Thank you @Vinnl! I'll merge in and then add some additional decoration.

**Comment by Vinnl** [comment]
Excellent, thanks!

**Comment by xolotl** [comment]
Let me know if the RSS now at http://jrost.org doesn't seem right to you.

**Comment by Vinnl** [comment]
My feed reader recognised it, so I guess it's right now :)

**Pull request merged**
